version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=1
      - APP_KEY=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=test_app
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=test_app
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "33060:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:


