version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    ports:
      - "8700:80"
    volumes:
      - ./:/var/www/html
      - vendor_data:/var/www/html/vendor
    environment:
      - APP_ENV=local
      - APP_DEBUG=1
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=test_app
      - DB_USERNAME=root
      - DB_PASSWORD=root
    command: >
      sh -lc "if [ ! -f vendor/autoload.php ]; then composer install --no-dev --prefer-dist --no-progress --no-interaction; fi; \
      if [ ! -f .env ] && [ -f .env.example ]; then cp .env.example .env; fi; \
      php artisan key:generate --force || true; \
      chmod -R 775 storage bootstrap/cache || true; \
      php artisan migrate --force || true; \
      exec apache2-foreground"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=test_app
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "53306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

volumes:
  db_data:
  vendor_data:


